name: oh-smoke
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - xarray
  - netcdf4
  - matplotlib
  - seaborn
  - cartopy
  - jupyterlab
  - ipykernel
  - tqdm
  - cftime
  - bottleneck
